---
$schema: https://raw.githubusercontent.com/streetsidesoftware/cspell/main/cspell.schema.json
version: '0.2'
dictionaryDefinitions:
  - name: custom-words
    path: './custom-words.txt'
    addWords: true
dictionaries:
  - custom-words
ignorePaths:
  - 'node_modules'
  - '/custom-words.txt'
