site_name: Enterprise Policy As Code (EPAC)
site_url: https://azure.github.io/enterprise-azure-policy-as-code/
repo_url: https://github.com/Azure/enterprise-azure-policy-as-code
docs_dir: Docs
theme:
  logo: Images/epac_svg.svg
  favicon: Images/epac_svg.svg
  language: en
  name: material
  font:
    text: Roboto
  palette:
    primary: black
    accent: blue
  features:
    - navigation.instant
    - navigation.indexes
    - navigation.sections:
        level: 1
    - content.code.annotate
    - content.tabs.link
    - content.code.copy
nav:
  - Home: index.md
  - Overview:
      - Core Concepts: overview/concepts.md
      - Breaking Changes & Migration Notes: overview/breaking-changes.md
      - Ecosystem: overview/ecosystem.md
  - Getting Started:
      - Overview and Prerequisites: getting-started/README.md
      - Hydration Kit: getting-started/hydration-kit.md
      - Manual Configuration: getting-started/manual-setup.md
      - Extracting Policy Resources: getting-started/extracting-existing.md
      - Forking GitHub Repo: getting-started/forking-repo.md
  - Configuration:
      - Global Settings: configuration/global-settings.md
      - Desired State: configuration/desired-state.md
      - DfC Assignments: configuration/dfc-assignments.md
      - Output Themes: configuration/output-themes.md
      - Advanced Configuration: configuration/advanced.md
  - Azure Landing Zones:
      - ALZ Overview: integrations/alz-overview.md
      - ALZ Policy Integration: integrations/alz-library.md
  - Define Policy Resources:
      - Policy Definitions: policy-resources/policyDefinitions.md
      - Policy Set Definitions: policy-resources/policySetDefinitions.md
      - Policy Assignments: policy-resources/policyAssignments.md
      - CSV & JSON Parameters: policy-resources/assignments-csv.md
      - Policy Exemptions: policy-resources/policyExemptions.md
  - CI/CD Integration:
      - CI/CD Overview: ci-cd/README.md
      - App Registrations Setup: ci-cd/app-registrations.md
      - Branching Flows: ci-cd/branching-flows.md
      - Azure DevOps Pipelines: ci-cd/azure-devops.md
      - GitHub Actions: ci-cd/github-actions.md
  - Operational Scripts:
      - Scripts Overview: operations/README.md
      - Documenting Policy: operations/documenting-policy.md
      - Reference: operations/script-reference.md
  - Operator Guidance:
      - Remediation Enforcement: operations/remediation.md
      - Exclusion Management: guidance/scope-exclusions.md
      - Exemption Updates: operations/exemptions-workflow.md
      - Lighthouse Subscription Management: guidance/lighthouse.md
      - Debugging EPAC: troubleshooting/debugging.md

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
