name: 'Reusable Workflow: Remediation'

on:
  workflow_call:
    inputs:
      pacEnvironmentSelector:
        required: true
        type: string
      planGitHubEnvironment:
        required: true
        type: string
      PAC_DEFINITIONS_FOLDER:
        required: true
        type: string

env:
  pacEnvironmentSelector: ${{ inputs.pacEnvironmentSelector }}
  PAC_DEFINITIONS_FOLDER: ${{ inputs.PAC_DEFINITIONS_FOLDER }}

jobs:
  remediation:
    runs-on: ubuntu-latest
    environment: ${{ inputs.planGitHubEnvironment }}
    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          enable-AzPSSession: true
          allow-no-subscriptions: true

      - name: PolicyRemediation
        uses: azure/powershell@v2
        with:
          inlineScript: 'Scripts/Operations/New-AzRemediationTasks.ps1 -PacEnvironmentSelector ${{ env.pacEnvironmentSelector }} -OnlyCheckManagedAssignments -Interactive $false -InformationAction Continue'
          azPSVersion: "latest"