#Requires -PSEdition Core

# Define ./Scripts location in repo based on it being the parent of the Helpers directiory in which this script is located
$scriptRoot = Split-Path $PSScriptRoot -Parent

# Load cmdlets
. "$PSScriptRoot/Add-ErrorMessage.ps1"
. "$PSScriptRoot/Add-SelectedPacArray.ps1"
. "$PSScriptRoot/Add-SelectedPacValue.ps1"

. "$PSScriptRoot/Build-AssignmentDefinitionAtLeaf.ps1"
. "$PSScriptRoot/Build-AssignmentDefinitionEntry.ps1"
. "$PSScriptRoot/Build-AssignmentDefinitionNode.ps1"
. "$PSScriptRoot/Build-AssignmentIdentityChanges.ps1"
. "$PSScriptRoot/Build-AssignmentParameterObject.ps1"
. "$PSScriptRoot/Build-AssignmentPlan.ps1"

. "$PSScriptRoot/Build-ExemptionsPlan.ps1"
. "$PSScriptRoot/Build-PolicyPlan.ps1"
. "$PSScriptRoot/Build-PolicySetPlan.ps1"
. "$PSScriptRoot/Build-PolicySetPolicyDefinitionIds.ps1"

. "$PSScriptRoot/Build-ScopeTableForDeploymentRootScope.ps1"
. "$PSScriptRoot/Build-ScopeTableForManagementGroup.ps1"
. "$PSScriptRoot/Build-ScopeTableForSubscription.ps1"

. "$PSScriptRoot/Compare-SemanticVersion.ps1"

. "$PSScriptRoot/Confirm-EffectIsAllowed.ps1"
. "$PSScriptRoot/Confirm-MetadataMatches.ps1"
. "$PSScriptRoot/Confirm-NullOrEmptyValue.ps1"
. "$PSScriptRoot/Confirm-PacOwner.ps1"
. "$PSScriptRoot/Confirm-DeleteForStrategy.ps1"
. "$PSScriptRoot/Confirm-ObjectValueEqualityDeep.ps1"
. "$PSScriptRoot/Confirm-ParametersDefinitionMatch.ps1"
. "$PSScriptRoot/Confirm-ParametersUsageMatches.ps1"
. "$PSScriptRoot/Confirm-PolicyDefinitionUsedExists.ps1"
. "$PSScriptRoot/Confirm-PolicyDefinitionsInPolicySetMatch.ps1"
. "$PSScriptRoot/Confirm-PolicyDefinitionsParametersMatch.ps1"
. "$PSScriptRoot/Confirm-PolicyResourceExclusions.ps1"
. "$PSScriptRoot/Confirm-PolicySetDefinitionUsedExists.ps1"
. "$PSScriptRoot/Confirm-ValidPolicyResourceName.ps1"

. "$PSScriptRoot/Convert-AllowedEffectsToCsvString.ps1"
. "$PSScriptRoot/Convert-EffectToOrdinal.ps1"
. "$PSScriptRoot/Convert-EffectToMarkdownString.ps1"
. "$PSScriptRoot/Convert-EffectToCsvString.ps1"
. "$PSScriptRoot/Convert-OrdinalToEffectDisplayName.ps1"
. "$PSScriptRoot/Convert-ParametersToString.ps1"
. "$PSScriptRoot/Convert-PolicyResourcesDetailsToFlatList.ps1"
. "$PSScriptRoot/Convert-PolicyResourcesDetailsToFlatList-Documentation.ps1"
. "$PSScriptRoot/Convert-PolicyResourcesToDetails.ps1"
. "$PSScriptRoot/Convert-PolicySetToDetails.ps1"
. "$PSScriptRoot/Convert-PolicyToDetails.ps1"
. "$PSScriptRoot/ConvertTo-ArrayList.ps1"
. "$PSScriptRoot/ConvertTo-HashTable.ps1"

. "$PSScriptRoot/Export-AssignmentNode.ps1"
. "$PSScriptRoot/Find-AzNonCompliantResources.ps1"

. "$PSScriptRoot/Get-AzPolicyOrSetDefinitions.ps1"
. "$PSScriptRoot/Get-AzPolicyAssignments.ps1"
. "$PSScriptRoot/Get-AzPolicyExemptions.ps1"
. "$PSScriptRoot/Get-AzPolicyResources.ps1"
. "$PSScriptRoot/Get-AzPolicyResourcesDetails.ps1"
. "$PSScriptRoot/Get-CalculatedPolicyAssignmentsAndReferenceIds.ps1"
. "$PSScriptRoot/Get-CustomMetadata.ps1"
. "$PSScriptRoot/Get-DeepCloneAsOrderedHashtable.ps1"
. "$PSScriptRoot/Get-DefinitionsFullPath.ps1"
. "$PSScriptRoot/Get-DeploymentPlan.ps1"
. "$PSScriptRoot/Get-GlobalSettings.ps1"
. "$PSScriptRoot/Get-PacFolders.ps1"
. "$PSScriptRoot/Get-ParameterNameFromValueString.ps1"
. "$PSScriptRoot/Get-PolicyAssignmentsDetails.ps1"
. "$PSScriptRoot/Get-PolicyResourceProperties.ps1"
. "$PSScriptRoot/Get-ScrubbedString.ps1"

. "$PSScriptRoot/Merge-AssignmentParametersEx.ps1"
. "$PSScriptRoot/Merge-ExportNodeAncestors.ps1"
. "$PSScriptRoot/Merge-ExportNodeChild.ps1"

. "$PSScriptRoot/New-ErrorInfo.ps1"
. "$PSScriptRoot/New-ExportNode.ps1"

. "$PSScriptRoot/Out-PolicyAssignmentFile.ps1"
. "$PSScriptRoot/Out-DocumentationForPolicyAssignments.ps1"
. "$PSScriptRoot/Out-PolicyDefinition.ps1"
. "$PSScriptRoot/Out-PolicyExemptions.ps1"
. "$PSScriptRoot/Out-DocumentationForPolicySets.ps1"

. "$PSScriptRoot/Remove-NullFields.ps1"
. "$PSScriptRoot/Remove-GlobalNotScopes.ps1"

. "$PSScriptRoot/Search-AzGraphAllItems.ps1"
. "$PSScriptRoot/Select-PacEnvironment.ps1"

. "$PSScriptRoot/Set-AzCloudTenantSubscription.ps1"
. "$PSScriptRoot/Set-ExportNode.ps1"
. "$PSScriptRoot/Set-ExportNodeAncestors.ps1"
. "$PSScriptRoot/Set-UniqueRoleAssignmentScopes.ps1"


. "$PSScriptRoot/Split-ArrayIntoChunks.ps1"
. "$PSScriptRoot/Split-AzPolicyResourceId.ps1"
. "$PSScriptRoot/Split-HashtableIntoChunks.ps1"

. "$PSScriptRoot/Submit-EPACTelemetry.ps1"

. "$PSScriptRoot/Switch-PacEnvironment.ps1"
. "$PSScriptRoot/Convert-ObjectToComparableJson.ps1"
. "$PSScriptRoot/ConvertTo-DisplayString.ps1"
. "$PSScriptRoot/Get-SelectorArrays.ps1"
. "$PSScriptRoot/Write-AssignmentDetails.ps1"
. "$PSScriptRoot/Write-DetailedDiff.ps1"
. "$PSScriptRoot/Write-ErrorsFromErrorInfo.ps1"
. "$PSScriptRoot/Write-ModernOutput.ps1"

. "$PSScriptRoot/RestMethods/Get-AzManagementGroupRestMethod.ps1" 
. "$PSScriptRoot/RestMethods/Get-AzPolicyAssignmentRestMethod.ps1"
. "$PSScriptRoot/RestMethods/Get-AzPolicyExemptionsRestMethod.ps1"
. "$PSScriptRoot/RestMethods/Get-AzResourceListRestMethod.ps1"
. "$PSScriptRoot/RestMethods/Get-AzRoleAssignmentsRestMethod.ps1"
. "$PSScriptRoot/RestMethods/Get-AzRoleDefinitionsRestMethod.ps1"
. "$PSScriptRoot/RestMethods/Remove-AzResourceByIdRestMethod.ps1"   
. "$PSScriptRoot/RestMethods/Remove-AzRoleAssignmentRestMethod.ps1"
. "$PSScriptRoot/RestMethods/Set-AzPolicyAssignmentRestMethod.ps1"
. "$PSScriptRoot/RestMethods/Set-AzPolicyDefinitionRestMethod.ps1"
. "$PSScriptRoot/RestMethods/Set-AzPolicySetDefinitionRestMethod.ps1"
. "$PSScriptRoot/RestMethods/Set-AzPolicyExemptionRestMethod.ps1"
. "$PSScriptRoot/RestMethods/Set-AzRoleAssignmentRestMethod.ps1"

# Hydration Kit Content

. "$PSScriptRoot/Build-HydrationAssignmentPlan.ps1"
. "$PSScriptRoot/Build-HydrationPolicyPlan.ps1"
. "$PSScriptRoot/Build-HydrationPolicySetPlan.ps1"
. "$PSScriptRoot/Compare-HydrationMetadata.ps1"
. "$PSScriptRoot/Copy-HydrationOrderedHashtable.ps1"
. "$PSScriptRoot/Export-HydrationObjectToJsonFile.ps1"
. "$PSScriptRoot/Get-HydrationChildManagementGroupNameList.ps1"
. "$PSScriptRoot/Get-HydrationDefinitionSubfolderByContentId.ps1"
. "$PSScriptRoot/Get-HydrationEpacRepo.ps1"
. "$PSScriptRoot/Get-HydrationUserObjectId.ps1"
. "$PSScriptRoot/Join-HydrationHashtableToPath.ps1"
. "$PSScriptRoot/New-HydrationAnswerFile.ps1"
. "$PSScriptRoot/New-HydrationAnswerSet.ps1"
. "$PSScriptRoot/New-HydrationChangeEntry.ps1"
. "$PSScriptRoot/New-HydrationContinuePrompt.ps1"
. "$PSScriptRoot/New-HydrationManagementGroupChildren.ps1"
. "$PSScriptRoot/New-HydrationMenuResponse.ps1"
. "$PSScriptRoot/New-HydrationMultipleChoicePrompt.ps1"
. "$PSScriptRoot/New-HydrationSeparatorBlock.ps1"
. "$PSScriptRoot/Remove-HydrationChildHierarchy.ps1"
. "$PSScriptRoot/Test-HydrationAccess.ps1"
. "$PSScriptRoot/Test-HydrationCaf3Hierarchy.ps1"
. "$PSScriptRoot/Update-HydrationModuleToSupportedVersion.ps1"
. "$PSScriptRoot/Update-HydrationStarterKitAssignmentScope.ps1"
. "$PSScriptRoot/Write-HydrationLogFile.ps1"

. "$PSScriptRoot/../HydrationKit/Build-HydrationDeploymentPlans.ps1"
. "$PSScriptRoot/../HydrationKit/Copy-HydrationManagementGroupHierarchy.ps1"
. "$PSScriptRoot/../HydrationKit/Install-HydrationEpac.ps1"
. "$PSScriptRoot/../HydrationKit/New-FilteredExceptionFile.ps1"
. "$PSScriptRoot/../HydrationKit/New-HydrationAssignmentPacSelector.ps1"
. "$PSScriptRoot/../HydrationKit/New-HydrationCaf3Hierarchy.ps1"
. "$PSScriptRoot/../HydrationKit/New-HydrationDefinitionsFolder.ps1"
. "$PSScriptRoot/../HydrationKit/New-HydrationGlobalSettingsFile.ps1"
. "$PSScriptRoot/../HydrationKit/New-HydrationPolicyDocumentationSourceFile.ps1"
. "$PSScriptRoot/../HydrationKit/Remove-HydrationManagementGroupRecursively.ps1"
. "$PSScriptRoot/../HydrationKit/Test-HydrationConnection.ps1"
. "$PSScriptRoot/../HydrationKit/Test-HydrationManagementGroupName.ps1"
. "$PSScriptRoot/../HydrationKit/Test-HydrationPath.ps1"
. "$PSScriptRoot/../HydrationKit/Test-HydrationRbacAssignment.ps1"
. "$PSScriptRoot/../HydrationKit/Update-HydrationAssignmentDestination.ps1"
. "$PSScriptRoot/../HydrationKit/Update-HydrationDefinitionFolderStructureByAssignment.ps1"