name: Sync ALZ Policy Objects

# DEPRECATED: This workflow uses an outdated sync process.
# Please refer to the documentation for the new Azure Landing Zone Library sync process:
# https://azure.github.io/enterprise-azure-policy-as-code/integrating-with-alz-library/
#
# The new process requires:
# 1. Creating a policy default structure file using New-ALZPolicyDefaultStructure
# 2. Using Sync-ALZPolicyFromLibrary instead of the removed Sync-ALZPolicies function
#
# For a working example, see the Azure DevOps pipeline template:
# StarterKit/Pipelines/AzureDevOps/GitHub-Flow/epac-alz-sync-pipeline.yml

env:
  REVIEWER: anwather # Change this to your GitHub username
  DefinitionsRootFolder: Definitions # Change this to the folder where your policy definitions are stored
  PacEnvironmentSelector: epac-dev # Change this to your PAC environment selector
  ALZLibraryType: ALZ # Change this to ALZ, AMBA, or SLZ as needed

on:
  workflow_dispatch

jobs:
    sync:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout
          uses: actions/checkout@v4
        - shell: pwsh
          name: Install Required Modules and Sync
          run: |
            Install-Module EnterprisePolicyAsCode -Force
            # Note: You must have a policy default structure file created before running this workflow
            # See: https://azure.github.io/enterprise-azure-policy-as-code/integrating-with-alz-library/
            Sync-ALZPolicyFromLibrary -DefinitionsRootFolder $env:DefinitionsRootFolder -Type $env:ALZLibraryType -PacEnvironmentSelector $env:PacEnvironmentSelector
            $branchName = "caf-sync-$(Get-Date -Format yyyy-MM-dd-HH-mm)"
            git config user.name "GitHub Actions Bot"
            git config user.email "<>"
            git checkout -b $branchName
            git add .
            git commit -m "Updated ALZ policy objects"
            git push --set-upstream origin $branchName
            gh pr create -B main -H $branchName --title "Verify Synced Policies - $branchName" -b "Checkout this PR branch and validate changes before merging." --reviewer $env:REVIEWER
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}