name: Build Deployment Plan

env:
  REVIEWER: anwather # Change this to a GitHub reviewer
  pacEnvironment: gh-action # Change this to a PAC environment name
  definitionsRootFolder: Definitions
  planFolder: Output

on:
  push:
    paths:
      - Definitions/**

jobs:
  build:
    name: Build Deployment Plan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.3.0
      - name: Check for NO_ACTIONS
        shell: pwsh
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          if (Get-ChildItem -Path $env:definitionsRootFolder -Filter "NO_ACTIONS" -Recurse) {
            Write-Output "NO_ACTIONS file found, exiting"
            gh run cancel ${{ github.run_id }}
            gh run watch ${{ github.run_id }}
          }
      - shell: pwsh
        name: Install Required Modules
        run: |
          Install-Module Az.ResourceGraph -Force -AllowClobber
          Install-Module Az.Resources -Force -AllowClobber
          Install-Module EnterprisePolicyAsCode -Force
      - name: Azure Login
        uses: Azure/login@v1
        with:
          creds: '{"clientId":"${{ secrets.CLIENT_ID }}","clientSecret":"${{ secrets.CLIENT_SECRET }}","subscriptionId":"${{ secrets.SUBSCRIPTION_ID }}","tenantId":"${{ secrets.TENANT_ID }}"}'
          enable-AzPSSession: true
      - name: Build Deployment Plan
        uses: azure/powershell@v1
        with:
          inlineScript: |
            Build-DeploymentPlans -definitionsRootFolder $env:definitionsRootFolder -outputFolder $env:planFolder -pacEnvironment $env:pacEnvironment
            $epacInfoStream | Set-Content body.txt
          azPSVersion: "latest"
      - shell: pwsh
        name: Detect Plan
        run: |
          if (Get-ChildItem -Path $env:definitionsRootFolder -Filter "NO_DEPLOY" -Recurse) {
            Write-Output "NO_DEPLOY file found, exiting"
            gh run cancel ${{ github.run_id }}
            gh run watch ${{ github.run_id }}
          }
          if (Test-Path $env:planFolder) {
            echo "Deploy=true" >> $env:GITHUB_ENV
            if (!(Get-ChildItem $env:planFolder -Recurse -Include policy-plan.json)){
              echo "RolesOnly=true" >> $env:GITHUB_ENV
            }
          }
      - shell: pwsh
        name: Create PR
        if: ${{ env.Deploy == 'true' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          Remove-Item .gitignore -Verbose -Force
          $branchName = "automated-pr-$(Get-Date -Format yyyy-MM-dd-HH-mm)"
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"
          git checkout -b $branchName
          git add .
          git commit -m "Deployment plan commit"
          git push --set-upstream origin $branchName
          if ($env:RolesOnly -eq "true") {
            gh pr create -B main -H $branchName --title "Approval Required for Role Deployment - $branchName" -F body.txt --reviewer $env:REVIEWER --label RoleDeployment
          }
          else {
            gh pr create -B main -H $branchName --title "Approval Required for Policy Deployment - $branchName" -F body.txt --reviewer $env:REVIEWER --label PolicyDeployment
          }
          
