# This pipeline is used to deploy Policies, Initiative definitions and Assignments into Azure.
name: EPAC NONPROD Workflow

on:
  push:
    branches:
      - main

env:
  PAC_OUTPUT_FOLDER: ./Output
  PAC_DEFINITIONS_FOLDER: ./Definitions

permissions:
  contents: read
  id-token: write

jobs:
  plan:
    name: Plan nonprod
    uses: ./.github/workflows/plan.yml
    with:
      pacEnvironmentSelector: nonprod
      planGitHubEnvironment: NONPROD-PLAN
      PAC_OUTPUT_FOLDER: ./Output
      PAC_DEFINITIONS_FOLDER: ./Definitions
    secrets: inherit

  deployPolicy:
    name: Deploy nonprod Policy Changes
    needs: plan
    if: needs.plan.outputs.deployPolicyChanges == 'yes' && github.ref == 'refs/heads/main'
    uses: ./.github/workflows/deploy-policy.yml
    with:
      pacEnvironmentSelector: nonprod
      planGitHubEnvironment: NONPROD-DEPLOY-POLICY
      PAC_INPUT_FOLDER: ./Output
      PAC_DEFINITIONS_FOLDER: ./Definitions
    secrets: inherit

  deployRoles:
    name: Deploy nonprod Role Changes
    needs: plan
    if: needs.plan.outputs.deployRoleChanges == 'yes' && github.ref == 'refs/heads/main'
    uses: ./.github/workflows/deploy-roles.yml
    with:
      pacEnvironmentSelector: nonprod
      planGitHubEnvironment: NONPROD-DEPLOY-ROLES
      PAC_INPUT_FOLDER: ./Output
      PAC_DEFINITIONS_FOLDER: ./Definitions
    secrets: inherit