name: Publish Module

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: checkout
        uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4.4.0
      - shell: pwsh
        env:
          APIKEY: ${{ secrets.APIKEY }}
          TAG_NAME: ${{ github.event.release.tag_name }}
        run: |
          # Install-Module Az.ResourceGraph -Force
          .\Module\build.ps1
          Publish-Module -Path .\Module\EnterprisePolicyAsCode -NuGetApiKey $env:APIKEY -Verbose
          
          
