name: Deploy Policy Roles

env:
  REVIEWER: andrewybarra # Change this to a GitHub reviewer
  pacEnvironment: EPAC-Staging # Change this to a PAC environment name
  definitionsRootFolder: Definitions
  planFolder: Output

on:
  workflow_run:
    workflows: ["Deploy Policy Plan"]
    types:
      - completed

jobs:
  deploy:
    name: Deploy Policy Roles
    if: github.event.review.state == 'approved'
    runs-on: ubuntu-latest
    environment: 
      name: ${{ vars.PAC_SELECTOR }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3.3.0
      - shell: pwsh
        name: Install Required Modules
        run: |
          Install-Module Az.ResourceGraph -Force -Verbose -AllowClobber
          Install-Module Az.Resources -Force -Verbose -AllowClobber
          Install-Module EnterprisePolicyAsCode -Force
      - name: Azure Login
        uses: Azure/login@v1
        with:
          creds: '{"clientId":"${{ secrets.CLIENT_ID }}","clientSecret":"${{ secrets.CLIENT_SECRET }}","subscriptionId":"${{ secrets.SUBSCRIPTION_ID }}","tenantId":"${{ secrets.TENANT_ID }}"}'
          enable-AzPSSession: true
      - name: Deploy Role Plan
        if: contains(github.event.pull_request.labels.*.name, 'RoleDeployment')
        uses: azure/powershell@v1
        with:
          inlineScript: |
            Deploy-RolesPlan -definitionsRootFolder $env:definitionsRootFolder -inputFolder $env:planFolder -pacEnvironment $env:pacEnvironment
          azPSVersion: "latest"
      - shell: pwsh
        if: contains(github.event.pull_request.labels.*.name, 'RoleDeployment')
        name: Confirm PR
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_NUMBER: ${{ github.event.pull_request.number }}
        run: |
          gh pr close $env:PR_NUMBER --comment 'Changes deployed' --delete-branch
          
