name: Octo Organization CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

steps: 
- name: PowerShell script
-uses: Amadevus/pwsh-script@v2.0.3
  with:
    # PowerShell script to execute in Actions-hydrated context
    script: "Scripts/CloudAdoptionFramework/Sync-CAFPolicies.ps1"
