name: build-docs
on:
  push:
    branches:
      - main

permissions: 
  pages: write
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4.4.0
      - uses: actions/setup-python@e9aba2c848f5ebd159c070c61ea2c4e2b122355e # v2.3.4
        with:
          python-version: 3.x
      - run: pip install mkdocs mkdocs-material
      - name: ConvertAlerts
        shell: pwsh
        run: |
          mkdir tmp
          ./Scripts/Operations/Convert-MarkdownGitHubAlerts.ps1 -InputFolder ./Docs -OutputFolder ./tmp
          Move-Item -Path ./tmp/* -Destination ./Docs -Force
      - run: mkdocs gh-deploy --force --clean --verbose
